import { useState } from "react";
import { Copy, Check, Square, ShieldAlert, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export function Disclaimer() {
  return (
    <div className="flex gap-3 rounded-xl border border-brand/30 bg-accent p-4 text-sm text-accent-foreground">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" />
      <p>
        <strong>Responsible AI:</strong> outputs are generated by AI and may contain errors, omissions or bias.
        Always review, edit and verify facts before sending or acting on them, and avoid entering confidential or
        personal data.
      </p>
    </div>
  );
}

export function OutputPanel({
  output,
  setOutput,
  loading,
  error,
  stop,
}: {
  output: string;
  setOutput: (v: string) => void;
  loading: boolean;
  error: string | null;
  stop: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <section className="flex min-w-0 flex-col gap-3 rounded-2xl border bg-card p-5 shadow-card">
      <div className="flex items-center justify-between gap-2">
        <h2 className="flex items-center gap-2 text-base font-semibold">
          Result {loading && <Loader2 className="h-4 w-4 animate-spin text-brand" />}
        </h2>
        <div className="flex gap-2">
          {loading && (
            <Button size="sm" variant="outline" onClick={stop}>
              <Square className="h-3.5 w-3.5" /> Stop
            </Button>
          )}
          <Button size="sm" variant="outline" onClick={copy} disabled={!output}>
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied" : "Copy"}
          </Button>
        </div>
      </div>
      {error && <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
      <Textarea
        value={output}
        onChange={(e) => setOutput(e.target.value)}
        placeholder="Your AI-generated result will appear here. You can edit it freely."
        className="min-h-[360px] flex-1 resize-y font-sans text-sm leading-relaxed"
        aria-label="Editable AI output"
      />
      <p className="text-xs text-muted-foreground">Editable — review and refine before using.</p>
    </section>
  );
}

export function FieldLabel({ children, htmlFor }: { children: React.ReactNode; htmlFor?: string }) {
  return (
    <label htmlFor={htmlFor} className="mb-1.5 block text-sm font-medium">
      {children}
    </label>
  );
}

export function GenerateButton({ loading, children }: { loading: boolean; children: React.ReactNode }) {
  return (
    <Button type="submit" disabled={loading} className="w-full bg-brand text-brand-foreground hover:bg-brand/90 shadow-glow">
      {loading && <Loader2 className="h-4 w-4 animate-spin" />}
      {children}
    </Button>
  );
}
